image: node:18

cache:
  paths:
    - node_modules/

default:
  before_script:
    - corepack disable # prevent auto Yarn v4 activation
    - npm install -g yarn@1.22.22
    - yarn install

stages:
  - test
  - build
  - release

lint_and_test:
  stage: test
  script:
    - yarn lint
    - yarn test

  rules:
    - if: '$CI_COMMIT_BRANCH == "gitlabci" && $CI_PIPELINE_SOURCE == "web"'
      when: always

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist/
  rules:
    - if: '$CI_COMMIT_BRANCH == "gitlabci" && $CI_PIPELINE_SOURCE == "web"'
      when: always

release:
  stage: release
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish
  rules:
    - if:
        '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]-gitlabci\.[0-9]+$/ &&
        $CI_PIPELINE_SOURCE == "web"'
      when: always
