image: node:18-alpine

cache:
  paths:
    - node_modules/

workflow:
  rules:
    - if:
        '($CI_COMMIT_BRANCH == "gitlabci" || $CI_COMMIT_TAG) &&
        $CI_PIPELINE_SOURCE == "api"'
      when: always
    - when: never

default:
  before_script:
    - corepack disable # prevent auto Yarn v4 activation
    - npm install -g yarn@1.22.22
    - yarn install

stages:
  - test
  - build
  - release

lint_and_test:
  stage: test
  script:
    - yarn lint
    - yarn test

build:
  stage: build
  script:
    - yarn build
    - echo 'CI_COMMIT_TAG value -> "$CI_COMMIT_TAG"'
  needs:
    - lint_and_test
  artifacts:
    paths:
      - dist/

release:
  stage: release
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - echo "Publishing version -> $(node -p
      "require('./package.json').version")" # print package version before publishing
    - npm publish
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]-gitlabci\.[0-9]+$/'
      when: on_success
