version: 2.1

# This is a minimal debug configuration to find the exact git tag value.
# After you find the value, you can use it to fix your regex.

executors:
  # A simple executor is all we need for a single echo command.
  node_executor:
    docker:
      - image: cimg/node:18.20

jobs:
  print_tag_name:
    executor: node_executor
    steps:
      - run:
          name: Print the exact git tag value
          # This command will output the value of the pipeline parameter.
          # The output will be in the format 'CircleCI Pipeline Tag: <your_tag_name>'.
          command: |
            echo "CircleCI Pipeline Tag: << pipeline.git.tag >>"

workflows:
  version: 2.1
  # This workflow is configured to run for ANY tag push.
  # The `only: /.*/` regex ensures it always triggers on a tag.
  debug_tag_workflow:
    jobs:
      - print_tag_name:
          filters:
            branches:
              ignore: /.*/ # Ignore all branches
            tags:
              only: /.*/ # Run for any tag
