version: 2.1

# Define reusable executor
executors:
  node_executor:
    docker:
      - image: cimg/node:18.20

anchors:
  tag_filter: &tag_filter
    tags:
      only: /^v\d+\.\d+\.\d+-circleci\.\d+$/ # Updated regex to match the corrected tag format
  branch_filter: &branch_filter
    branches:
      only: circleci

      <<: *branch_filter
      <<: *tag_filter

# Define all the jobs
jobs:
  install:
    executor: node_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-deps-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint_and_test:
    executor: node_executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint
      - run: yarn test

  build:
    executor: node_executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish:
    executor: node_executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with npm
          command: |
            # Use the NPM_TOKEN environment variable for authentication
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm publish

# Consolidate workflows into a single, filtered workflow
workflows:
  version: 2.1
  build_and_release:
    jobs:
      - install:
          filters:
            <<: *branch_filter
            <<: *tag_filter
      - lint_and_test:
          requires:
            - install
          filters:
            <<: *branch_filter
            <<: *tag_filter
      - build:
          requires:
            - lint_and_test
          filters:
            b<<: *branch_filter
            <<: *tag_filter
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/ # Ignore all branches
            <<: *tag_filter
