# this is how the final config_continued.yml file will look after preprocessor.sh concatenates modular files
# Circle CI config split up in modules
# https://medium.com/%40philblenk6/circleci-config-splitting-7024bad400e3
# https://github.com/blenky36/circleci-config-splitting?source=post_page-----7024bad400e3---------------------------------------
# this file is dynamically loaded by the setup config if file changes are detected
version: 2.1
# this parameter will be passed from the path-filtering orb.
# it is set to 'true' if the file regexes in config.yml have a match
parameters:
  run-build-and-release:
    type: boolean
    default: false
# Define reusable executor
executors:
  node_executor:
    docker:
      # - image: cimg/node:18.20
      # updated: using the lightweight 'node:18-alpine' image for faster download in ci setup and faster pipelines
      - image: node:18-alpine

anchors:
  tag_filter: &tag_filter
    tags:
      only: /^v\d+\.\d+\.\d+-circleci\.\d+$/ # Updated regex to match the corrected tag format
  branch_filter: &branch_filter
    branches:
      only: circleci

jobs:
  install:
    executor: node_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
      #updated: install git and yarn. Alpine based images are very minimal and
      # may not have git or yarn pre-installed
      - run: apk add --no-cache git
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-deps-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint_and_test:
    executor: node_executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint
      - run: yarn test

  build:
    executor: node_executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish:
    executor: node_executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with npm
          command: |
            # Use the NPM_TOKEN environment variable for authentication
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - run: npm publish

# Consolidate workflows into a single, filtered workflow
workflows:
  version: 2.1
  build_and_release:
    when: << pipeline.parameters.run-build-and-release >>
    jobs:
      - install:
          filters:
            <<: *branch_filter
            <<: *tag_filter
      - lint_and_test:
          requires:
            - install
          filters:
            <<: *branch_filter
            <<: *tag_filter
      - build:
          requires:
            - lint_and_test
          filters:
            <<: *branch_filter
            <<: *tag_filter
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/ # Ignore all branches
            <<: *tag_filter
