image: node:18-alpine

include:
  project: 'arsalanshaikh13/Parallax-Provider-Tutorial'
  ref: gitlabci
  file:
    - '.gitlab/lint_and_test/lint_and_test.yml'
    - '.gitlab/build/build.yml'
    - '.gitlab/release/release.yml'

# default:
#   # global cache for node_modules directory
#   # cache key is based on yarn.lock file.
#   # this ensures cache is only recreated if a dependency is added,updated, or removed

.cache_common: &cache_common
  key:
    files:
      - yarn.lock
  paths:
    - node_modules/

stages:
  - test
  - build
  - release

lint_and_test:
  cache:
    <<: *cache_common

build:
  needs:
    - job: lint_and_test
      artifacts: false # don't download lint_and_test artifacts
  cache:
    <<: *cache_common
    policy: pull

release:
  needs:
    - build
  cache:
    <<: *cache_common
    policy: pull
