lint_and_test:
  executor: node_executor
  steps:
    - checkout
    - attach_workspace:
        at: /app
    - run: pwd
    - run: ls node_modules | grep eslint
    - run: yarn lint
    - run: yarn test
