publish:
  executor: node_executor
  steps:
    # - checkout
    - attach_workspace:
        at: /app
    - run:
        name: Authenticate with npm
        command: |
          # Use the NPM_TOKEN environment variable for authentication
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
    - run: npm publish
