docker_project:
  docker:
    - image: docker:20.10-git

  steps:
    - run:
        name: git sparse-checkout clone
        command: |
          git clone --no-checkout --sparse --depth=1 "https://${GITHUB_USERNAME}:${GITHUB_PULL_TOKEN}@github.com/${GITHUB_USERNAME}/Parallax-Provider-Tutorial.git"
          git sparse-checkout set --no-cone "project/*"
          git checkout HEAD
    - setup_remote_docker: # gives you a remote Docker engine
        docker_layer_caching: true
    - run:
        name: Build Image and Push to DockerHub
        command: |
          cd project
          docker build -t arsalanshaikh13/parallaxwebpage:${CIRCLE_SHA1} .
          echo $DOCKERHUB_PAT | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push arsalanshaikh13/parallaxwebpage:${CIRCLE_SHA1}
