image: node:18-alpine

# default:
#   # global cache for node_modules directory
#   # cache key is based on yarn.lock file.
#   # this ensures cache is only recreated if a dependency is added,updated, or removed
#   cache:
#     key:
#       files:
#         - yarn.lock
#     paths:
#       - node_modules/
stages:
  - test
  - build
  - release

lint_and_test:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: on_success
    - when: never

  script:
    - yarn install --frozen-lockfile --ignore-scripts
    - yarn lint
    - yarn test
  coverage: /All files[^|]*|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/clover.xml
    expire_in: 1 day
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/

build:
  stage: build
  needs:
    - job: lint_and_test
      artifacts: false # don't download lint_and_test artifacts
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: on_success
    - when: never

  script:
    - yarn install --frozen-lockfile --ignore-scripts
    - yarn build

  # save the build artifacts ('dist' folder) so they can pass to the publish stage
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull
release:
  stage: release
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    - echo "Publishing version -> $(node -p
      "require('./package.json').version")" # print package version before publishing
    - npm publish --ignore-scripts # ignore running scripts in package.json
    # since publish needs build stage to happen anyway so no need to put the anchor here
    # it will only run if build successfully happens
  needs:
    - build
  rules:
    - if:
        '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]-gitlabci\.[0-9]+$/ &&
        $CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: on_success
