name: Lint, Test and Build
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install  --frozen-lockfile
      shell: bash

    - name: Lint
      run: yarn lint
      shell: bash

    - name: Test
      run: yarn test
      shell: bash

    - name: Build
      run: yarn build
      shell: bash

    - name: Upload build artifacts (dist/)
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
