name: Build, Test and Publish

on:
  push:
    branches:
      - main
    tags:
      - '/^v[0-9]+.*$' # Trigger release when pushing tags like v1.0.0

jobs:
  build-and-test:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Upload build artifacts (dist/)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

publish:
  name: Publish to npm
  needs: build-and-test
  runs-on: ubuntu-latest
  if: startwith(github.ref, 'refs/tags/v') # only on version tags

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: yarn install --ignore-scripts

    - name: Download build artifacts (dist/)
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
