name: Build, Test and Publish

on:
  push:
    branches:
      - main
      # git does not take regex patterns but takes glob patterns
      # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#filter-pattern-cheat-sheet
    tags:
      - 'v[0-9].[0-9]+.[0-9]+' # Trigger release when pushing tags like v1.0.0

jobs:
  filter-changes:
    uses: ./.github/workflows/filter-changes.yml

  test-and-build:
    # This job will only run if the 'filter-changes' job's output is 'true'.
    # This is the key to skipping the entire job on empty commits.
    needs: filter-changes
    # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/pass-job-outputs
    if: needs.filter-changes.outputs.has_relevant_changes == 'true'
    uses: ./.github/workflows/test_and_build.yml

  publish:
    needs: test-and-build
    if: startswith(github.ref, 'refs/tags/v') # only on version tags
    uses: ./.github/workflows/publish.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
