# https://support.circleci.com/hc/en-us/articles/360050351292-How-to-Trigger-a-Workflow-via-CircleCI-API-v2
# https://circleci.com/docs/triggers-overview/#trigger-a-pipeline-from-a-custom-webhook
name: Trigger CircleCI

on:
  push:
    branches:
      - circleci
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI pipeline
        run: |
          curl -X POST https://circleci.com/api/v2/project/gh/arsalanshaikh13/Parallax-Provider-Tutorial/pipeline \
            --header "Circle-Token: ${CIRCLECI_TOKEN}" \
            --header "Content-Type: application/json" \
            --data '{"branch": "circleci"}'

        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
