# https://support.circleci.com/hc/en-us/articles/360050351292-How-to-Trigger-a-Workflow-via-CircleCI-API-v2
name: Trigger CircleCI

on:
  push:
    branches:
      - circleci
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI pipeline
        run: |
          curl -X POST -H "content-type: application/json" "https://internal.circleci.com/private/soc/e/22ffdd2d-c668-4039-8b23-8845cf825072?secret=Es6uEflzZZrUDlVp8UVMPD4R2rqTe5w5lOgMkLbqC8o="

        env:
          CIRCLECI_WEBHOOK_URL: ${{ secrets.CIRCLECI_WEBHOOK_URL }}
