name: Filter Changes

on:
  workflow_call:
    outputs:
      has_relevant_changes:
        description: 'Check whether relevant files changed'
        value: ${{ jobs.filter-changes.outputs.has_relevant_changes }}
jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      # https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#outputs-for-docker-container-and-javascript-actions
      has_relevant_changes: ${{ steps.check-changes.outputs.has_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # fetch last 2 commit
        with:
          fetch-depth: 2

      - name: Check for relevant file changes
        id: check-changes
        run: |
          set +e
          # Use git diff to find changes between the previous commit and the current one.
          # The grep command filters for the file extensions you specified.
          # The result is saved as a step output, which can be used in other jobs.
          # capture the error and show it the output
          changed_files=$(git diff --name-only  HEAD^ ${{ github.sha }} 2>&1 | grep -E '\.js$|\.json$|\.yml$|\.lock$|\..*rc$')
          echo $changed_files output
          if [ -n "$changed_files" ]; then
            echo "Relevant files have been changed."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No relevant files were changed. Skipping subsequent jobs."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
