name: Sync and Trigger GitLab CI

on:
  workflow_dispatch:
  push:
    branches:
      - gitlabci # or your branch
    tags:
      - 'v*-gitlabci.*'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v4
        with:
          # Set fetch-depth to include previous commits for proper syncing with GitLab.
          # Explanation:
          # - Provides a buffer of recent commits to handle cases where previous GitHub Actions
          #   runs failed, ensuring GitLab receives all necessary commits.
          # - Adjust fetch-depth based on your push frequency (to avoid shallow commit errors):
          #   * Frequent pushes: fetch-depth 2 is usually sufficient.
          #   * Less frequent (e.g., 10 commits at a time): set fetch-depth to 10.
          #   * Always account for any failed GitHub Actions .
          fetch-depth: 5 # Include the last 5 commits to ensure git rev-parse works in gitlab-sync-and-trigger.sh
      - name: Push to Gitlab and Trigger GitLab Pipeline
        run: bash ./ci-scripts/gitlab-sync-and-trigger.sh
        env:
          GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }} # gitlab pipeline trigger token
          GITLAB_PUSH_TOKEN: ${{ secrets.GITLAB_PUSH_TOKEN }} # gitlab personal access token with api, write and read repository scope
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
          GITLAB_BRANCH: ${{ secrets.GITLAB_BRANCH }}
          # GITLAB_PAT: ${{ secrets.GITLAB_PAT}} # gitlab project access token with role owner and api and read repository and write repository scope
