name: Sync and Trigger GitLab CI

on:
  workflow_dispatch:
  push:
    branches:
      - gitlabci # or your branch
    tags:
      - 'v*-gitlabci.*'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v4
        with:
          # setting fetch-depth:5 as buffer to provide the commits from the latest commit to previous successful pushed
          # since my last 2 pushes on github action failed gitlab didn't get the last 2 commits
          # actuall gitlab wants to sync the github repo with gitlab repo so keep the fetch-depth equivalent to no of commits pushing to github actions for build
          # if we are frequently pushing to github then fetch-depth 2 will work (to make git rev-parse also work)
          # if we are pushing to github after every 10 commits then fetch-depth should be 10 (assuming there were no errors in github actions)
          # if there were error in github actions then we have to account for that commit
          # keeping all this in mind we have to set fetch-depth value
          fetch-depth: 5 # sending previous 5 commits to avoid shallow commit error and make git rev-parse work in gitlab-sync-and-trigger.sh file

      - name: Push to Gitlab and Trigger GitLab Pipeline
        run: bash ./ci-scripts/gitlab-sync-and-trigger.sh
        env:
          GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }} # gitlab pipeline trigger token
          GITLAB_PUSH_TOKEN: ${{ secrets.GITLAB_PUSH_TOKEN }} # gitlab personal access token with api, write and read repository scope
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
          GITLAB_BRANCH: ${{ secrets.GITLAB_BRANCH }}
          GITLAB_PAT: ${{ secrets.GITLAB_PAT}} # gitlab project access token with role owner and api and read repository and write repository scope
