name: Sync and Trigger GitLab CI

on:
  push:
    branches:
      - gitlabci # or your branch
    tags:
      - 'v*-gitlabci.*'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # clone full history, avoids shallow push rejection

      - name: Push to Gitlab and Trigger GitLab Pipeline
        run: bash ./ci-scripts/gitlab-sync-and-trigger.sh
        env:
          GITLAB_PUSH_TOKEN: ${{ secrets.GITLAB_PUSH_TOKEN }}
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
          GITLAB_BRANCH: ${{ secrets.GITLAB_BRANCH }}
          GITLAB_PAT: ${{ secrets.GITLAB_PAT}}
