name: Publish to npm

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/publish/
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
