name: Trigger GitLab CI

on:
  push:
    branches:
      - gitlabci # or your branch

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitLab Pipeline
        env:
          GITLAB_TRIGGER_TOKEN: ${{  secrets  }}
        run: |
          echo "Triggering Gitlab pipeline..."
          echo "Token (first 4 chars):$GITLAB_TRIGGER_TOKEN ${{  secrets  }}" # debug optional
          curl -X POST "https://gitlab.com/api/v4/projects/72053714/trigger/pipeline" \
            -H "Content-Type: application/json" \
            -d "{\"token\": \"${GITLAB_TRIGGER_TOKEN}\", \"ref\": \"gitlabci\"}"
