name: Trigger GitLab CI

on:
  push:
    branches:
      - gitlabci # or your branch

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitLab Pipeline
        env:
          GITLAB_TRIGGER_TOKEN: ${{  secrets.GITLAB_TRIGGER_TOKEN  }}
          GITLAB_PAT: ${{ secrets.GITLAB_PAT}}
        run: |
          curl -X POST "https://gitlab.com/api/v4/projects/72053714/trigger/pipeline" \
            -H "PRIVATE-TOKEN: $GITLAB_PAT" \
            -H "Content-Type: application/json" \
            -d "{ \"ref\": \"gitlabci\"}"
