name: Trigger GitLab CI

on:
  push:
    branches:
      - gitlabci # or your branch

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Debug secret
        env:
          GITLAB_TRIGGER_TOKEN: ${{  secrets.GITLAB_TRIGGER_TOKEN  }}
        run: |
          if [ -z "$GITLAB_TRIGGER_TOKEN" ]; then
            echo " Secret missing"
            exit 1
          else
            echo " Secret exists"
          fi

      - name: Trigger GitLab Pipeline
        run: |
          echo "Triggering Gitlab pipeline..."
          echo "Token (first 4 chars):$GITLAB_TRIGGER_TOKEN ${{  secrets.GITLAB_TRIGGER_TOKEN  }}" # debug optional
          curl -X POST "https://gitlab.com/api/v4/projects/72053714/trigger/pipeline" \
            -H "Content-Type: application/json" \
            -d "{\"token\": \"glptt-a7e828a89257cdf81a1686c60cafd9c27a23548d\", \"ref\": \"gitlabci\"}"
